### ISSUE TITLE
RFI for use in hMailserver Vbscript

### ISSUE THREAD

**Issue by gotspatel** [kimboslice99/AbuseIPDBCacheComponent#1]
I was able to build the project to DLL but I am unable to use it in hmailserver (no programming knowledge)

Could to please provide more information how to use it in hmailserver to check the ip details and report if required)

Getting error for sqlite, (HOW to provide the SQLite DB?

TIA

I tried using as below

```
Function IsBlockedByAbuseIPDB(strIP)
    ' Create an instance of the AbuseIPDBClient ActiveX object
    Dim restClient
    Set restClient = CreateObject("AbuseIPDBCacheComponent.AbuseIPDBClient")
    
    ' Set the API key, confidence score, and age parameters
    restClient.SetApiKey "MY_API_KEY"
    restClient.SetMaxConfidenceScore 60
    restClient.SetMaxAgeInDays 30
    
    ' Check if the IP is blocked
    Dim Blocked
    Blocked = restClient.Block(strIP)
    WScript.Echo "IS BLOCKED: " & Blocked
    ' Get the abuse confidence score
    Dim Score
    Score = restClient.GetAbuseConfidenceScore()
    WScript.Echo "ScoreIP: " & Score
    ' Check if the data is from cache
    Dim fromCache
    fromCache = restClient.IsFromCache()
    
    ' Optionally, you can extract other data, like Tor, ISP, and total reports
    ' Dim isTor
    ' isTor = restClient.IsTor()
    ' Dim Isp
    ' Isp = restClient.GetISP()
    ' Dim totalReports
    ' totalReports = restClient.GetTotalReports()
    
    ' Log information (you can implement your logging mechanism here)
    If DEBUG Then
       WScript.Echo "INFO: IsFromCache: " & fromCache & " IsSuccess: " & restClient.IsSuccess()
    End If

    ' If blocked, log the IP and the score
    If Blocked Then
        WScript.Echo "Blocked: " & strIP & " ListedInAbuseIPDB Score: " & Score
    End If

    ' Return the result of whether the IP is blocked
    IsBlockedByAbuseIPDB = Blocked
End Function



IPAddress1 = "78.128.112.86"
result = IsBlockedByAbuseIPDB(IPAddress1)
WScript.Echo result
```

**Comment by kimboslice99** [comment]
db is created and managed automatically, sounds like perhaps a build issue?

I would recommend changing hmailservers scripting to JScript (look in settings) and use the provided examples.

I will create an installer in the near future.

**Comment by gotspatel** [comment]
Thank you I will Wait since I use vbscript for others can't change hmailservers scripting to JScript.

Do we have to provide the sqlite db path anywhere during the build?, I just tried the build from the GUI of Visual Studio as I was getting error for sqlite while using msbuild from cmd prompt,  I will try. (I am getting rate limit a lot, and really looking forward to this)

TIA

**Comment by kimboslice99** [comment]
I have built and released an installer, have a look in the [releases section](https://github.com/kimboslice99/AbuseIPDBCacheComponent/releases)

here's a vbscript example
```vbscript
Function IsBlockedByAbuseIPDB(strIP) : ListedInAbuseIPDB = false
	With CreateObject("AbuseIPDBCacheComponent.AbuseIPDBClient")
		.SetApiKey("YOURAPIKEY")
		.SetMaxConfidenceScore(40)
		.SetMaxAgeInDays(30)
		On Error Resume Next
		ListedInAbuseIPDB = .Block(strIP)
		If (ListedInAbuseIPDB) then
			WScript.Echo("AbuseIPDB Score:" & .GetAbuseConfidenceScore())
		End If
		If Err.Number <> 0 Then
			WScript.Echo("AbuseIPDB Error: " & Err.Description)
		End If
		On Error Goto 0
	End With
    IsBlockedByAbuseIPDB = ListedInAbuseIPDB
End Function


If IsBlockedByAbuseIPDB("144.86.26.142") Then
    WScript.Echo("LISTED")
End If
```

**Comment by kimboslice99** [comment]
@LogicMaven Noticed I made some mistakes with the installer. I have uploaded a fresh build, so if you were still having trouble please do make another attempt to install (uninstall old version first via control panel)

**Comment by gotspatel** [comment]
I knew something was off but not sure
THANK YOU

**Comment by kimboslice99** [comment]
I assume you have had success then? I plan to spend more time with this installer and code so be on the lookout for updates.

Configurable cache time is going to be added along with some other things

**Comment by gotspatel** [comment]
> Configurable cache time is going to be added along with some other things

Really Important as I think 6 hours Cache is good for very busy servers instead of 1 hour (default now)

**Comment by LogicMaven** [comment]
@kimboslice99 

with VBScript I get this error can you please advise

`fun AbuseIPDB Cache.vbs(4, 3) Microsoft VBScript runtime error: Object doesn't support this property or method: 'SetMaxConfidenceScore'`

**Comment by gotspatel** [comment]
@kimboslice99 

with VBScript I get this error can you please advise

`fun AbuseIPDB Cache.vbs(4, 3) Microsoft VBScript runtime error: Object doesn't support this property or method: 'SetMaxConfidenceScore'`

**Comment by gotspatel** [comment]
Never Mind Got it working, This is the Vbscript 

```
Function IsBlockedByAbuseIPDB(strIP) : ListedInAbuseIPDB = false
	With CreateObject("AbuseIPDBCacheComponent.AbuseIPDBClient")
		On Error Resume Next
		ListedInAbuseIPDB = .Block(strIP)
		If (ListedInAbuseIPDB) then
			WScript.Echo("AbuseIPDB Score:" & .GetAbuseConfidenceScore())
		End If
		If Err.Number <> 0 Then
			WScript.Echo("AbuseIPDB Error: " & Err.Description)
		End If
		On Error Goto 0
	End With
    IsBlockedByAbuseIPDB = ListedInAbuseIPDB
End Function


If IsBlockedByAbuseIPDB("95.84.142.172") Then
    WScript.Echo("LISTED")
End If

```

**Comment by kimboslice99** [comment]
SetMaxConfidenceScore is now more aptly named SetMinConfidenceScore, and is configurable both statically via the config or at runtime.
